// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TMAutoNewGame","status":false,"description":"起動時に自動ではじめからゲームを開始します。\r\nWeb用ミニゲームなど、タイトル画面が不要な場合などにどうぞ。","parameters":{"autoNewGame":"0","firstLimited":"2","allwaysOnTop":"0","autoDevTool":"1","autoContinueCommand":"自動コンティニュー","blockKey":"control"}},
{"name":"TMServerRTP","status":false,"description":"ひとつ上の階層にある audio, img を参照することで、複数の\r\nプロジェクトで画像、音声ファイルを共用します。","parameters":{"defaultLoadSystem":"0"}},
{"name":"TMCard","status":true,"description":"デッキ構成で勝敗が決まるタイプのカードゲームが\r\n遊べるようになります。","parameters":{"vnResult":"1","vnMaxDeck":"2","vnMaxCard":"3","vnMaxCost":"4","fixCardNum":"0","sameCard":"1","useItemCard":"1","useAutoText":"1","commandDeckEdit":"デッキ編集","statusWindowWidth":"360","maxAtk":"8","maxTurn":"50","animationDamage":"1","animationTypeBonus":"52","paramNames":"名前 レア度 コスト ＨＰ 攻撃力 タイプ スキル 固有スキル 継承スキル 属性","itemCardParamNames":"ため時間 基本効果 特殊効果","typeIcons":"76 77 81 79 176","typeSpeed":"1 4 0 2","elementIcons":"64 65 66 67 68 69 70 71","rareNames":"Common Uncommon Rare Legend","costIcon":"87","costIconSpace":"20","positionNames":"1st 2nd 3rd 4th 5th","itemCardPositionName":"ITM","deckNames":"デッキＡ デッキＢ デッキＣ デッキＤ デッキＥ","playerCardPositions":"128,264 272,184 368,184 464,184 560,184","playerItemCardPosition":"272,344","enemyCardPositions":"688,264 544,344 448,344 352,344 256,344","enemyItemCardPosition":"544,184","numberPositions":"128,488 208,456 688,488 608,456"}}
];
